### ISSUE TITLE
Error in code generation dialog

### ISSUE THREAD

**Issue by ericbodden** [eclipse-cognicrypt/CogniCrypt#240]
In Eclipse Neon, when I start the code-generation dialog and select something in the tree, I see the error shown in the screenshot.

![screenshot 2019-01-08 at 10 13 47](https://user-images.githubusercontent.com/1862846/50820988-56f79400-132e-11e9-8c11-b2fbc85e3048.png)

**Comment by akwick** [comment]
In Eclipse Oxygen (Release 4.7.2), I receive probably the same error when trying to generate the code. 

> !ENTRY org.eclipse.ui 4 0 2019-01-11 11:13:09.964
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at de.cognicrypt.codegenerator.generator.CodeGenerator.insertCallCodeIntoFile(CodeGenerator.java:161)
	at de.cognicrypt.codegenerator.generator.XSLBasedGenerator.generateCodeTemplates(XSLBasedGenerator.java:119)
	at de.cognicrypt.codegenerator.wizard.AltConfigWizard.performFinish(AltConfigWizard.java:206)
	at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:778)
	at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:417)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at de.cognicrypt.codegenerator.actions.WizardAction.run(WizardAction.java:67)
	at org.eclipse.ui.internal.PluginAction.runWithEvent(PluginAction.java:247)
	at org.eclipse.ui.internal.WWinPluginAction.runWithEvent(WWinPluginAction.java:219)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)

**Comment by kruegers** [comment]
Hey @ericbodden,
Could you please provide more details to facilitate reproduction of the bug? I went through the code generation with both the current master branch and the update site version and it worked without error.

Hey @akwick,
In my experience, this error only occurs under certain circumstances. Could you please provide details of your setup (and potentially open a new issue for it)?

Thanks.

**Comment by kruegers** [comment]
Hey @akwick,

I've run the code generation multiple times today on a different computer with Eclipse 2018-12 and it worked like a charm. Can you perhaps try whether you still get the error on a newer Eclipse?

Hey @enriozuni, @AndreSonntag, and @shahrzadav,
Is any of you still using an Eclipse < Eclipse Photon? If so, please pull from the master branch, test the code generation, and report here whether it works. Thanks.

**Comment by enriozuni** [comment]
@kruegers Unfortunately, I don't. I use the latest version of Eclipse

**Comment by shahrzadav** [comment]
@kruegers Sorry, I use Oxygen 3a version.

**Comment by kruegers** [comment]
@shahrzadav That's good because Oxygen is older than Photon. Can you please test the code generation?

**Comment by akwick** [comment]
@kruegers In Eclipse 2018-12 the error seems to be solved or in other words: I can't reproduce it anymore.

I only observed the error directly after starting on the first two trials (selection Project and Package). After it worked once on the third selection, all following tries (File, Project, restart Eclipse with CogniCrypt, Project, Package, File, restart Eclipse for development, new Project) succeded.

**Comment by kruegers** [comment]
Thanks, @akwick. 
@ericbodden Is there any chance you could either provide more details or update to a more recent Eclipse version and try again? If it is Eclipse Neon itself, that is causing the problem, I would rather close the issue. Neon has been out for two and a half years and I wouldn't want to put too much effort into supporting an Eclipse version that is so old.

**Comment by shahrzadav** [comment]
@kruegers Ive tried it and it works fine for me. I get no Errors.

**Comment by kruegers** [comment]
Thanks, @shahrzadav. Then, the problem is either more specific or it is really caused by the interaction of CogniCrypt and the Eclipse Neon platform.

**Comment by kruegers** [comment]
Closed for the time being because bug could not be reproduced in multiple attempts. Please re-open, when it can be.
