### ISSUE TITLE
Error message appears on every save/compile

### ISSUE THREAD

**Issue by johspaeth** [eclipse-cognicrypt/CogniCrypt#280]
**Describe the bug**
I receive an error message whenever I modify one of my Java-files in some of my project, i.e., whenever the compiler built the project.

> Errors occurred during the build.
> Errors running builder 'CrySL Builder' on project 'Project A'. Path must include project and resource name: /Project B

**Comment by johspaeth** [comment]
Attached is a stack trace for the finding. The project `boomerangPDS` does not even contain any CrySL rules. 
```
java.lang.IllegalArgumentException: Path must include project and resource name: /boomerangPDS
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2120)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at de.cognicrypt.crysl.reader.CrySLModelReader.readRules(CrySLModelReader.java:216)
	at de.cognicrypt.crysl.handler.CrySLBuilder.build(CrySLBuilder.java:47)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
