### ISSUE TITLE
Error message appears on every save/compile of CrySL rule

### ISSUE THREAD

**Issue by rakshitkr** [eclipse-cognicrypt/CogniCrypt#282]
**Describe the bug**
I receive the following error message whenever I modify one of crysl rules and save it.

```
Errors occurred during the build.
Errors running builder 'CrySL Builder' on project 'CryptSL Examples'.
java.lang.NullPointerException
```

**Comment by rakshitkr** [comment]
Attached is a stack trace for the finding.

```
!ENTRY de.cognicrypt.crysl.handler 1 0 2019-04-30 13:46:36.282
!MESSAGE ResourcechangeListener has been triggered.

!ENTRY de.cognicrypt.core 4 0 2019-04-30 13:46:36.283
!MESSAGE 
!STACK 0
java.lang.NullPointerException
	at de.cognicrypt.utils.Utils.getResourceFromWithin(Utils.java:306)
	at de.cognicrypt.crysl.handler.StartupHandler$AfterBuildListener.resourceChanged(StartupHandler.java:77)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:365)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:157)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.core.resources 4 2 2019-04-30 13:46:36.284
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NullPointerException
	at de.cognicrypt.crysl.handler.StartupHandler$AfterBuildListener.resourceChanged(StartupHandler.java:77)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:290)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:153)
	at org.eclipse.core.internal.resources.Workspace.broadcastBuildEvent(Workspace.java:365)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:157)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by kruegers** [comment]
Not reproducible with the latest version on either my or Rakshit's machine. Closing it for now.
